# login

POST http://localhost:3001/edusearch_login
Content-Type: application/json

{
    "username": "anewtest2",
    "password": "Anewtest2!"
}

###
# signup

POST http://localhost:3001/edusearch_signup
Content-Type: application/json

{
    "username": "Jeff",
    "password": "Jeff777!",
    "email": "jeffzincatz@gmail.com"
}

