# login

POST http://localhost:3001/edusearch_login
Content-Type: application/json

{
    "username": "anewtest2",
    "password": "Anewtest2!"
}

###
# signup

POST http://localhost:3001/edusearch_signup
Content-Type: application/json

{
    "username": "anewtest7",
    "password": "Anewtest6!",
    "email": "anewtest7@gmail.com"
}

###
#send a faq
POST http://localhost:3001/faq
Content-Type: application/json

{
    "section": 1,
    "question": "test question",
    "answer": "test answer"
    
}